# Generated by Django 6.0.1 on 2026-01-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_haccpproducttype_companyhaccpowner_haccpdocument_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='haccpdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='haccpdocument',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = tenant master set', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='haccpdocument',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haccpproducttype',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='haccpproducttype',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='haccpdocument',
            unique_together={('tenant', 'company', 'product_type', 'document_type', 'year', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='haccpproducttype',
            unique_together={('tenant', 'slug')},
        ),
    ]
