# Generated by Django 4.2.7 on 2026-01-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zone_sopparent_sopchild_companyoperationconfig_sop_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycertificate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companyproducttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companycertificate',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyhaccpowner',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyproducttype',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='companycertificate',
            unique_together={('tenant', 'company', 'year', 'certificate_type')},
        ),
        migrations.AlterUniqueTogether(
            name='companyproducttype',
            unique_together={('tenant', 'company', 'product_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sopchild',
            unique_together={('sop_parent', 'sop_did')},
        ),
    ]
