# Generated by Django 4.2.7 on 2026-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companycertificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
