# Generated by Django 4.2.7 on 2026-01-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_tenantuser_is_admin_usercompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateField(blank=True, help_text='SOP effective date - only shows in inspections on/after this date', null=True),
        ),
    ]
