# Generated by Django 4.2.7 on 2026-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_po_so_sod_alter_purchaseorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Customer replies go here', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reply_to_name',
            field=models.CharField(blank=True, help_text='Display name for reply-to', max_length=255, null=True),
        ),
    ]
