# Generated by Django 4.2.7 on 2026-02-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tenant_reply_to_email_tenant_reply_to_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'documents_tenant_email',
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
