# Generated by Django 4.2.7 on 2026-02-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vehicle_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
    ]
