# Generated by Django 4.2.7 on 2026-02-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_license_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_sender', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='Unassigned', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('transcription', models.TextField(blank=True)),
                ('caller_phone', models.CharField(blank=True, max_length=50)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'order_request',
            },
        ),
    ]
