# Generated by Django 4.2.7 on 2026-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ms_client_id',
            field=models.CharField(blank=True, help_text='Azure App Client ID', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ms_client_secret',
            field=models.CharField(blank=True, help_text='Azure App Client Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ms_tenant_id',
            field=models.CharField(blank=True, help_text='Azure AD Tenant ID', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='order_email_address',
            field=models.EmailField(blank=True, help_text='Email address to check for orders', max_length=254, null=True),
        ),
    ]
