# Generated by Django 4.2.7 on 2026-02-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tenant_ms_client_id_tenant_ms_client_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('voicemail', 'Voicemail'), ('sms', 'SMS/Text')], default='email', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Unassigned', max_length=50)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'inbound_message',
            },
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='ms_client_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='ms_client_secret',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='ms_tenant_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='order_email_address',
        ),
        migrations.AddField(
            model_name='tenant',
            name='inbound_email_address',
            field=models.EmailField(blank=True, help_text='Email to check for orders/voicemails', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='inbound_email_imap_server',
            field=models.CharField(blank=True, default='imap.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='inbound_email_password',
            field=models.CharField(blank=True, help_text='App password', max_length=255),
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
