# Generated by Django 4.2.7 on 2026-02-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_inboundmessage_remove_tenant_ms_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='e.g. +18555975969', max_length=20),
        ),
    ]
