# Generated by Django 4.2.7 on 2026-03-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tenant_twilio_account_sid_tenant_twilio_auth_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_did', models.IntegerField(blank=True, null=True)),
                ('comp_item_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('comp_price_id', models.IntegerField(blank=True, null=True)),
                ('origin_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'profile_customerprofile',
                'ordering': ['description'],
            },
        ),
    ]
