# Generated by Django 4.2.7 on 2026-03-05 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customer_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('vendorid', models.CharField(blank=True, max_length=100)),
                ('receivedate', models.CharField(blank=True, max_length=50)),
                ('vendorlot', models.CharField(blank=True, max_length=100)),
                ('actualcost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unittype', models.CharField(blank=True, max_length=50)),
                ('unitsonhand', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unitsavailable', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unitsallocated', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unitsin', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unitsout', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unitsstored', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('weightin', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('weightout', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('billedweight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('availableweight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('casesavailable', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('casesonhand', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pendingunits', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('shelflife', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('critical', models.CharField(blank=True, max_length=100)),
                ('packdate', models.CharField(blank=True, max_length=50)),
                ('poid', models.CharField(blank=True, max_length=100)),
                ('podid', models.CharField(blank=True, max_length=100)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('storageid', models.IntegerField(blank=True, null=True)),
                ('flagged', models.IntegerField(default=0)),
                ('fixed', models.IntegerField(default=0)),
                ('hidden', models.IntegerField(default=0)),
                ('updatetime', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'inventory_inventory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'inventory_product',
                'unique_together': {('tenant', 'product_id')},
            },
        ),
    ]
