# Generated by Django 6.0.1 on 2026-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fishmenuitem_fishorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
