# Generated by Django 6.0.1 on 2026-04-02 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_lead_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('subscription_agreement', 'Subscription Agreement'), ('privacy_policy', 'Privacy Policy'), ('sla', 'Service Level Agreement')], max_length=50)),
                ('signing_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('signer_title', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'document_type')},
            },
        ),
    ]
