# Generated by Django 6.0.1 on 2026-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_tenant_document_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['sort_order', 'description']},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_retail',
            field=models.BooleanField(default=False, help_text='Retail customer - items appear on the Fish Market page'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
