# Generated by Django 6.0.1 on 2026-04-02 22:46

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_retail_customer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(help_text='1, 2, or 3')),
                ('image', models.ImageField(upload_to=core.models.product_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.customerprofile')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('profile', 'slot')},
            },
        ),
    ]
