# Generated by Django 6.0.1 on 2026-04-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_product_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='From address for outbound emails', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp-mail.outlook.com', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP login password', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='smtp_user',
            field=models.EmailField(blank=True, help_text='SMTP login email', max_length=254),
        ),
    ]
