# Generated by Django 6.0.1 on 2026-04-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_tenant_smtp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('pack_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_product',
                'ordering': ['sort_order', 'description'],
                'unique_together': {('tenant', 'description')},
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='tenant_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.tenantproduct'),
        ),
    ]
