# Generated by Django 6.0.1 on 2026-04-06 20:35

import django.db.models.deletion
from django.db import migrations, models


def copy_company_data_to_tenant(apps, schema_editor):
    """Copy logo/address/city/state/zipcode from Company to its Tenant."""
    Company = apps.get_model('core', 'Company')
    Tenant = apps.get_model('core', 'Tenant')
    for company in Company.objects.select_related('tenant').all():
        tenant = company.tenant
        if tenant:
            tenant.logo = company.logo or ''
            tenant.address = company.address or ''
            tenant.city = company.city or ''
            tenant.state = company.state or ''
            tenant.zipcode = company.zipcode or ''
            tenant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_product_image_to_tenant_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companycertificate',
            unique_together={('tenant', 'year', 'certificate_type')},
        ),
        migrations.AlterUniqueTogether(
            name='companyholiday',
            unique_together={('tenant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='companyproducttype',
            unique_together={('tenant', 'product_type')},
        ),
        migrations.AlterUniqueTogether(
            name='haccpdocument',
            unique_together={('tenant', 'product_type', 'document_type', 'year', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='sop',
            unique_together={('tenant', 'sop_did')},
        ),
        migrations.AlterUniqueTogether(
            name='sopparent',
            unique_together={('tenant', 'date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='tenant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunPython(copy_company_data_to_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='companycertificate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='companyhaccpowner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='companyholiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='companyoperationconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='companyproducttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='haccpdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='sop',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='sopparent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
