# Generated by Django 6.0.1 on 2026-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_company_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True),
        ),
    ]
