# Generated by Django 6.0.1 on 2026-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='signature',
            field=models.TextField(blank=True),
        ),
    ]
