# Generated by Django 6.0.1 on 2026-04-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_product_brand_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buying_piece_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='buying_unit_of_measure',
            field=models.CharField(blank=True, help_text='e.g. Bag, Case', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='buying_volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='buying_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. US Oysters, Fin Fish', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='habitat_production_method',
            field=models.CharField(blank=True, help_text='e.g. Wild, Farm Raised, Aquaculture', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_conversion',
            field=models.CharField(blank=True, help_text='e.g. 100 Each = 1 Bag', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_margin_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target profit margin %', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_piece_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_unit_of_measure',
            field=models.CharField(blank=True, help_text='e.g. Each, Lbs', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='species',
            field=models.CharField(blank=True, help_text='e.g. Eastern Oyster, Atlantic Salmon', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, help_text='Universal Product Code', max_length=100),
        ),
    ]
