# Generated by Django 6.0.1 on 2026-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_product_buying_piece_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cert',
            field=models.CharField(blank=True, help_text='Certification number', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mailing_zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(blank=True, help_text='e.g. Dealer, Exporter, Harvester', max_length=50),
        ),
    ]
