# Generated by Django 6.0.1 on 2026-04-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_processing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='processbatchoutput',
            name='yield_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yield % for this output', max_digits=6, null=True),
        ),
    ]
