# Generated by Django 6.0.1 on 2026-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_yield_percent_to_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, help_text='Storage location e.g. Cooler A', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='receive_time',
            field=models.CharField(blank=True, help_text='Time received e.g. 9:21 am', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor_type',
            field=models.CharField(blank=True, help_text='e.g. Dealer, Harvester', max_length=50),
        ),
    ]
