# Generated by Django 6.0.1 on 2026-04-15 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_purchasing_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('order_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('needs_review', 'Needs Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('packed_status', models.CharField(choices=[('not_packed', 'Not Packed'), ('packed', 'Packed'), ('need_to_send', 'Need To Send')], default='not_packed', max_length=20)),
                ('qb_invoice_number', models.CharField(blank=True, help_text='QuickBooks Invoice #', max_length=100)),
                ('sales_rep', models.CharField(blank=True, max_length=100)),
                ('po_number', models.CharField(blank=True, help_text='Customer PO number', max_length=100)),
                ('air_bill_number', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('pack_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('shipper', models.CharField(blank=True, max_length=255)),
                ('shipping_route', models.CharField(blank=True, max_length=100)),
                ('order_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in Lbs', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'sales_order',
                'ordering': ['-order_date', '-created_at'],
                'unique_together': {('tenant', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('item', 'Item'), ('fee', 'Fee')], default='item', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('margin', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'sales_order_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
