# Generated by Django 6.0.1 on 2026-04-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_legacy_po_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expected_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Expected weight from PO line item', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='po_item',
            field=models.ForeignKey(blank=True, help_text='Specific PO line item received against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_lots', to='core.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Linked purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_lots', to='core.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_variance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Received qty minus expected qty', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variance_flagged',
            field=models.BooleanField(default=False, help_text='True if variance exceeds threshold'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight_variance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Received weight minus expected weight (negative = short)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total quantity received against this line', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total weight received against this line', max_digits=12, null=True),
        ),
    ]
