# Generated by Django 6.0.1 on 2026-04-15 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_inventory_expected_weight_inventory_po_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processbatch',
            name='actual_yield_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield: output/input * 100', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='processbatch',
            name='expected_yield_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield from product catalog', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='processbatch',
            name='total_input_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sum of all source lot quantities', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='processbatch',
            name='total_output_weight',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sum of all output quantities', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='processbatch',
            name='yield_flagged',
            field=models.BooleanField(default=False, help_text='True if yield is significantly below expected'),
        ),
        migrations.AddField(
            model_name='processbatch',
            name='yield_variance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual minus expected yield', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='CCPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccp_type', models.CharField(choices=[('receiving_temp', 'Receiving Temperature'), ('processing_temp', 'Processing Room Temperature'), ('product_temp', 'Internal Product Temperature'), ('cooler_temp', 'Cooler/Storage Temperature'), ('sanitation', 'Sanitation Check'), ('other', 'Other')], max_length=30)),
                ('reading_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric reading (e.g. temperature in °F)', max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, default='°F', max_length=10)),
                ('critical_limit_min', models.DecimalField(blank=True, decimal_places=2, help_text='Lower acceptable limit', max_digits=8, null=True)),
                ('critical_limit_max', models.DecimalField(blank=True, decimal_places=2, help_text='Upper acceptable limit (e.g. 40°F for receiving)', max_digits=8, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('corrective', 'Corrective Action Taken')], default='pass', max_length=15)),
                ('out_of_range', models.BooleanField(default=False, help_text='Auto-set if reading exceeds limits')),
                ('location', models.CharField(blank=True, help_text='e.g. Dock, Processing Room, Cooler A', max_length=100)),
                ('description', models.CharField(blank=True, help_text='What was checked', max_length=255)),
                ('corrective_action', models.TextField(blank=True)),
                ('corrective_action_by', models.CharField(blank=True, max_length=100)),
                ('recorded_by_name', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, help_text='Lot this reading applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccp_logs', to='core.inventory')),
                ('process_batch', models.ForeignKey(blank=True, help_text='Processing batch this reading applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccp_logs', to='core.processbatch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'ccp_monitoring_log',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
