# Generated by Django 6.0.1 on 2026-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_processbatch_actual_yield_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('exception', 'Exception')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product temperature at delivery (°F)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pod_photo',
            field=models.CharField(blank=True, help_text='Path to delivery photo', max_length=500),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pod_signature',
            field=models.TextField(blank=True, help_text='Base64 signature from recipient'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Person who received the delivery', max_length=100),
        ),
    ]
