# Generated by Django 6.0.3 on 2026-04-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_receivingqualitycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='process_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='core.processbatch'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='process_source_lot_ids',
            field=models.TextField(blank=True, help_text='Comma-separated inventory IDs selected as process sources'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='process_type',
            field=models.CharField(blank=True, choices=[('fish_cutting', 'Fish Cutting'), ('commingle', 'Commingle'), ('renaming', 'Renaming'), ('freeze', 'Freeze'), ('lot_breaking', 'Bag or Lot Breaking'), ('shucking', 'Shucking'), ('wet_store', 'Wet Store')], max_length=30),
        ),
    ]
