from django.urls import path

from ..views.operations_api import (
    inventory_group_create,
    inventory_groups,
    inventory_item_create,
    inventory_item_delete,
    inventory_item_toggle_active,
    inventory_item_update,
    inventory_items,
    inventory_item_adjustment_create,
    inventory_item_adjustments,
    inventory_item_lots,
    inventory_items_export,
    product_orders,
    inventory_items_import,
    inventory_rejected_lots,
    operations_summary,
    processing_batch_cancel,
    processing_batch_delete,
    processing_batch_complete,
    processing_batch_outputs,
    processing_batch_sources,
    processing_batch_waste,
    processing_batch_waste_create,
    processing_batches,
    processing_batches_create,
    processing_batches_export,
    processing_source_lots,
    processing_batches_import,
    processing_products,
    processing_sold_results,
    processing_sold_result_delete,
    purchasing_order_create,
    purchasing_order_delete,
    purchasing_order_detail,
    purchasing_order_item_add,
    purchasing_order_item_delete,
    purchasing_order_update,
    purchasing_orders,
    purchasing_orders_export,
    purchasing_orders_import,
    receiving_lot_create,
    receiving_lot_delete,
    receiving_lot_detail,
    receiving_lot_quality,
    receiving_lots,
    receiving_lots_export,
    receiving_lots_import,
    receiving_open_pos,
    receiving_vendors,
    customer_create,
    customer_delete,
    customer_update,
    sales_customers,
    sales_order_allocate_fifo,
    sales_order_delete,
    sales_order_allocations,
    sales_order_detail_api,
    sales_order_item_add,
    sales_order_item_delete,
    sales_order_update,
    sales_orders,
    sales_orders_create,
    sales_orders_export,
    sales_orders_import,
    settings_account,
    settings_profile,
    settings_user_create,
    settings_user_delete,
    settings_user_update,
    settings_users,
    shipping_loading,
    shipping_log,
    shipping_log_export,
    trace_lookup,
    shipping_packing,
    shipping_picking,
    vendor_delete,
    vendor_update,
    vendors_create,
    vendors_export,
    vendors_import,
    vendors_list,
)


urlpatterns = [
    path("purchasing/orders/", purchasing_orders, name="api_purchasing_orders"),
    path("purchasing/orders/create/", purchasing_order_create, name="api_purchasing_order_create"),
    path("purchasing/orders/<int:order_id>/detail/", purchasing_order_detail, name="api_purchasing_order_detail"),
    path("purchasing/orders/<int:order_id>/update/", purchasing_order_update, name="api_purchasing_order_update"),
    path("purchasing/orders/<int:order_id>/delete/", purchasing_order_delete, name="api_purchasing_order_delete"),
    path("purchasing/orders/<int:order_id>/items/add/", purchasing_order_item_add, name="api_purchasing_order_item_add"),
    path(
        "purchasing/orders/<int:order_id>/items/<int:item_id>/delete/",
        purchasing_order_item_delete,
        name="api_purchasing_order_item_delete",
    ),
    path("receiving/vendors/", receiving_vendors, name="api_receiving_vendors"),
    path("receiving/lots/", receiving_lots, name="api_receiving_lots"),
    path("receiving/lots/create/", receiving_lot_create, name="api_receiving_lot_create"),
    path("receiving/lots/<int:lot_id>/", receiving_lot_detail, name="api_receiving_lot_detail"),
    path("receiving/lots/<int:lot_id>/quality/", receiving_lot_quality, name="api_receiving_lot_quality"),
    path("receiving/lots/<int:lot_id>/delete/", receiving_lot_delete, name="api_receiving_lot_delete"),
    path("receiving/open-pos/", receiving_open_pos, name="api_receiving_open_pos"),
    path("shipping/log/", shipping_log, name="api_shipping_log"),
    path("shipping/picking/", shipping_picking, name="api_shipping_picking"),
    path("shipping/packing/", shipping_packing, name="api_shipping_packing"),
    path("shipping/loading/", shipping_loading, name="api_shipping_loading"),
    path("operations/summary/", operations_summary, name="api_operations_summary"),
    path("processing/products/", processing_products, name="api_processing_products"),
    path("processing/source-lots/", processing_source_lots, name="api_processing_source_lots"),
    path("processing/sold-results/", processing_sold_results, name="api_processing_sold_results"),
    path("processing/sold-results/<int:batch_id>/<int:order_id>/delete/", processing_sold_result_delete, name="api_processing_sold_result_delete"),
    path("processing/batches/", processing_batches, name="api_processing_batches"),
    path("processing/batches/create/", processing_batches_create, name="api_processing_batches_create"),
    path("processing/batches/<int:batch_id>/sources/", processing_batch_sources, name="api_processing_batch_sources"),
    path("processing/batches/<int:batch_id>/outputs/", processing_batch_outputs, name="api_processing_batch_outputs"),
    path("processing/batches/<int:batch_id>/waste/", processing_batch_waste, name="api_processing_batch_waste"),
    path("processing/batches/<int:batch_id>/waste/create/", processing_batch_waste_create, name="api_processing_batch_waste_create"),
    path("processing/batches/<int:batch_id>/complete/", processing_batch_complete, name="api_processing_batch_complete"),
    path("processing/batches/<int:batch_id>/cancel/", processing_batch_cancel, name="api_processing_batch_cancel"),
    path("processing/batches/<int:batch_id>/delete/", processing_batch_delete, name="api_processing_batch_delete"),
    path("inventory/groups/", inventory_groups, name="api_inventory_groups"),
    path("inventory/groups/create/", inventory_group_create, name="api_inventory_group_create"),
    path("inventory/items/", inventory_items, name="api_inventory_items"),
    path("inventory/items/create/", inventory_item_create, name="api_inventory_item_create"),
    path("inventory/items/<int:item_id>/lots/", inventory_item_lots, name="api_inventory_item_lots"),
    path("inventory/items/<int:item_id>/adjustments/", inventory_item_adjustments, name="api_inventory_item_adjustments"),
    path("inventory/items/<int:item_id>/adjustments/create/", inventory_item_adjustment_create, name="api_inventory_item_adjustment_create"),
    path("inventory/items/<int:item_id>/update/", inventory_item_update, name="api_inventory_item_update"),
    path("inventory/items/<int:item_id>/delete/", inventory_item_delete, name="api_inventory_item_delete"),
    path("inventory/items/<int:item_id>/orders/", product_orders, name="api_product_orders"),
    path(
        "inventory/items/<int:item_id>/toggle-active/",
        inventory_item_toggle_active,
        name="api_inventory_item_toggle_active",
    ),
    path("settings/profile/", settings_profile, name="api_settings_profile"),
    path("settings/account/", settings_account, name="api_settings_account"),
    path("settings/users/", settings_users, name="api_settings_users"),
    path("settings/users/create/", settings_user_create, name="api_settings_user_create"),
    path("settings/users/<int:user_id>/update/", settings_user_update, name="api_settings_user_update"),
    path("settings/users/<int:user_id>/delete/", settings_user_delete, name="api_settings_user_delete"),
    path("sales/customers/", sales_customers, name="api_sales_customers"),
    path("sales/customers/create/", customer_create, name="api_customer_create"),
    path("sales/customers/<int:customer_id>/update/", customer_update, name="api_customer_update"),
    path("sales/customers/<int:customer_id>/delete/", customer_delete, name="api_customer_delete"),
    path("sales/orders/", sales_orders, name="api_sales_orders"),
    path("sales/orders/create/", sales_orders_create, name="api_sales_orders_create"),
    path("sales/orders/<int:order_id>/detail/", sales_order_detail_api, name="api_sales_order_detail"),
    path("sales/orders/<int:order_id>/update/", sales_order_update, name="api_sales_order_update"),
    path("sales/orders/<int:order_id>/items/add/", sales_order_item_add, name="api_sales_order_item_add"),
    path("sales/orders/<int:order_id>/items/<int:item_id>/delete/", sales_order_item_delete, name="api_sales_order_item_delete"),
    path("sales/orders/<int:order_id>/delete/", sales_order_delete, name="api_sales_order_delete"),
    path("sales/orders/<int:order_id>/allocations/", sales_order_allocations, name="api_sales_order_allocations"),
    path("sales/orders/<int:order_id>/allocate-fifo/", sales_order_allocate_fifo, name="api_sales_order_allocate_fifo"),
    path("sales/orders/export/", sales_orders_export, name="api_sales_orders_export"),
    path("sales/orders/import/", sales_orders_import, name="api_sales_orders_import"),
    path("purchasing/orders/export/", purchasing_orders_export, name="api_purchasing_orders_export"),
    path("purchasing/orders/import/", purchasing_orders_import, name="api_purchasing_orders_import"),
    path("receiving/lots/export/", receiving_lots_export, name="api_receiving_lots_export"),
    path("receiving/lots/import/", receiving_lots_import, name="api_receiving_lots_import"),
    path("processing/batches/export/", processing_batches_export, name="api_processing_batches_export"),
    path("processing/batches/import/", processing_batches_import, name="api_processing_batches_import"),
    path("inventory/export/", inventory_items_export, name="api_inventory_items_export"),
    path("inventory/import/", inventory_items_import, name="api_inventory_items_import"),
    path("inventory/rejected/", inventory_rejected_lots, name="api_inventory_rejected_lots"),
    path("vendors/list/", vendors_list, name="api_vendors_list"),
    path("vendors/create/", vendors_create, name="api_vendors_create"),
    path("vendors/<int:vendor_id>/update/", vendor_update, name="api_vendor_update"),
    path("vendors/<int:vendor_id>/delete/", vendor_delete, name="api_vendor_delete"),
    path("vendors/export/", vendors_export, name="api_vendors_export"),
    path("vendors/import/", vendors_import, name="api_vendors_import"),
    path("shipping/log/export/", shipping_log_export, name="api_shipping_log_export"),
    path("trace/", trace_lookup, name="api_trace_lookup"),
]
