from django.urls import path
from ..views.auth import operations_hub
from ..views.operations_reports import (
    generate_operational_report,
    generate_deviations_report,
    generate_bulk_report,
)
from ..views.operations_pages import (
    compliance_hub,
    inventory_item_detail_page,
    inventory_item_library,
    operations_admin,
    operations_dashboard,
    processing_detail,
    processing_hub,
    processing_new,
    purchase_detail_page,
    purchases_page,
    receiving_page,
    sales_orders_page,
    settings_page,
    shipping_hub,
    shipping_loading,
    shipping_packing,
    shipping_picking,
    trace_page,
    vendor_list_page,
)

urlpatterns = [
    path('', operations_hub, name='operations_hub'),
    path('purchases/', purchases_page, name='purchases_page'),
    path('purchases/<int:po_id>/', purchase_detail_page, name='purchase_detail_page'),
    path('receiving/', receiving_page, name='receiving_page'),
    path('inventory/', inventory_item_library, name='inventory_item_library'),
    path('inventory/<int:item_id>/', inventory_item_detail_page, name='inventory_item_detail'),
    path('processing/', processing_hub, name='processing_hub'),
    path('processing/new/', processing_new, name='processing_new'),
    path('processing/<int:batch_id>/', processing_detail, name='processing_detail'),
    path('sales/', sales_orders_page, name='sales_orders_page'),
    path('shipping/', shipping_hub, name='shipping_hub'),
    path('shipping/picking/', shipping_picking, name='shipping_picking'),
    path('shipping/packing/', shipping_packing, name='shipping_packing'),
    path('shipping/loading/', shipping_loading, name='shipping_loading'),
    path('settings/', settings_page, name='settings_page'),
    path('vendors/', vendor_list_page, name='vendor_list_page'),
    path('trace/', trace_page, name='trace_page'),
    path('compliance/', compliance_hub, name='compliance_hub'),
    path('compliance/dashboard/', operations_dashboard, name='operations_dashboard'),
    path('compliance/admin/', operations_admin, name='operations_admin'),
    path('report/operational/<int:parent_id>/', generate_operational_report, name='generate_operational_report'),
    path('report/deviations/<int:parent_id>/', generate_deviations_report, name='generate_deviations_report'),
    path('bulk-report/', generate_bulk_report, name='generate_bulk_report'),
]
